### ISSUE TITLE
Error while message sending {"code": "soon will be", "message": "Unknown error."}

### ISSUE THREAD

**Issue by Monsteryogi** [kirillzyusko/react-native-wifi-p2p-example#3]
I am using react-native-wifi-p2p in one of my project. as seen in logs and Wifi Direct network I am able to find Discover Devices and connect one of them. But when I try to send the message or file In Log Shows the Error "Error while message sending {"code": "soon will be", "message": "Unknown error."}"
I am using the same code given in repo for testing. So please help me to resolve it. 

Log of connect is
 "64646776467 {"groupFormed": true, "groupOwnerAddress": {"hostAddress": "192.168.49.1", "isLoopbackAddress": false}, "isGroupOwner": false}"

Log of getConnectionInfo() is
"{"groupFormed": true, "groupOwnerAddress": {"hostAddress": "192.168.49.1", "isLoopbackAddress": false}, "isGroupOwner": false}"

Thank you.

**Comment by JackTNorris** [comment]
Same error here. Any fix? Something in the docs says something about the method being unstable, so I'm assuming that it will be fixed in the future? Seems odd to even ship to npm if the basic functionality isn't quite complete

**Comment by kirillzyusko** [comment]
Hi @Monsteryogi and @JackTNorris 
I didn't notice this repository has issues :)
I'll close this issue.
If this issue is still actual - please, re-create an issue in the main repository. Thanks!
